# Generated by Django 3.0.4 on 2020-04-17 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pld',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время моследнего изменения'),
        ),
        migrations.AddField(
            model_name='pld',
            name='user_added',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем внесено/изменено'),
        ),
        migrations.AlterField(
            model_name='pld',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pld.PLDKind', verbose_name='Вид ПЛД'),
        ),
        migrations.AlterField(
            model_name='pld',
            name='pld_title',
            field=models.TextField(verbose_name='Название ПЛД'),
        ),
    ]
