# Generated by Django 3.0.4 on 2020-04-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0004_auto_20200409_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Основание')),
            ],
            options={
                'verbose_name': 'Основание для проведения исследования',
                'verbose_name_plural': 'Основания для проведения исследования',
                'ordering': ('reason',),
            },
        ),
        migrations.CreateModel(
            name='ResearchKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_name', models.CharField(max_length=255, verbose_name='Вид диссертационного исследования')),
            ],
            options={
                'verbose_name': 'Вид исследования',
                'verbose_name_plural': 'Виды исследований',
                'ordering': ('kind_name',),
            },
        ),
        migrations.CreateModel(
            name='ResearchPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Место проведения исследования',
                'verbose_name_plural': 'Места проведения исследований',
                'ordering': ('place',),
            },
        ),
        migrations.CreateModel(
            name='ResearchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255, verbose_name='Статус исследователя')),
            ],
            options={
                'verbose_name': 'Статус исследователя',
                'verbose_name_plural': 'Статусы исследователей',
                'ordering': ('status_name',),
            },
        ),
        migrations.CreateModel(
            name='DissertationResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.IntegerField(blank=True, null=True, verbose_name='Год начала')),
                ('date_end', models.IntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('date_protect', models.DateField(blank=True, null=True, verbose_name='Дата защиты')),
                ('dissertation_theme', models.TextField(verbose_name='Тема исследования')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат исследования')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='authors.Author', verbose_name='Автор исследования')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissertationresearch.ResearchKind', verbose_name='Вид исследования')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='authors.Author', verbose_name='Научный руководитель')),
                ('leader_subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_subdivision', to='authors.Subdivision', verbose_name='Подразделение научного руководителя')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissertationresearch.Reason', verbose_name='Основание для проведения исследования')),
                ('research_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissertationresearch.ResearchPlace', verbose_name='Место проведения исследования')),
                ('research_place_subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_place_subdivision', to='authors.Subdivision', verbose_name='Подразделение Академии МВД РБ (место проведения)')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissertationresearch.ResearchStatus', verbose_name='Статус исследователя')),
            ],
            options={
                'verbose_name': 'Диссертационное исследование',
                'verbose_name_plural': 'Диссертационные исследования',
                'ordering': ('id',),
            },
        ),
    ]
