# Generated by Django 3.0.3 on 2020-02-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatespecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_specialty_title', models.CharField(max_length=255, verbose_name='Название кандидатской диссертации')),
            ],
            options={
                'verbose_name': 'Кандидатская специальность',
                'verbose_name_plural': 'Кандидатские специальности',
                'ordering': ('candidate_specialty_title',),
            },
        ),
        migrations.CreateModel(
            name='Doctorspecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_specialty_title', models.CharField(max_length=255, verbose_name='Название докторской диссертации')),
            ],
            options={
                'verbose_name': 'Докторская специальность',
                'verbose_name_plural': 'Докторские специальности',
                'ordering': ('doctor_specialty_title',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('position_name',),
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100, verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subdivisiongroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivisiongroup_name', models.CharField(max_length=255, verbose_name='Группа подразделений')),
            ],
            options={
                'verbose_name': 'Группа подразделений',
                'verbose_name_plural': 'Группы подразделений',
                'ordering': ('subdivisiongroup_name',),
            },
        ),
        migrations.CreateModel(
            name='Workstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Рабочий статус')),
            ],
            options={
                'verbose_name': 'Рабочий статус',
                'verbose_name_plural': 'Рабочие статусы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_name', models.CharField(max_length=255, verbose_name='Наименование подразделения')),
                ('subdivision_short_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Сокращенное наименование подразделения')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Subdivisiongroup')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ('subdivision_name',),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('position_date', models.DateField(blank=True, null=True, verbose_name='Дата назначения на должность')),
                ('is_docentvak', models.BooleanField(default=False, verbose_name='Является доцентом ВАК')),
                ('docentvak_date', models.DateField(blank=True, null=True, verbose_name='Дата присовения доцента ВАК')),
                ('is_professor', models.BooleanField(default=False, verbose_name='Является профессором')),
                ('professor_date', models.DateField(blank=True, null=True, verbose_name='Дата присвоения профессороской степени')),
                ('is_candidate', models.BooleanField(default=False, verbose_name='Является кандидатом наук')),
                ('candidate_date', models.DateField(blank=True, null=True, verbose_name='Дата присвоения кандидата наук')),
                ('candidate_title', models.TextField(blank=True, null=True, verbose_name='Название кандидатской диссертации')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='Является доктором наук')),
                ('doctor_date', models.DateField(blank=True, null=True, verbose_name='Дата присвоения доктора наук')),
                ('doctor_title', models.TextField(blank=True, null=True, verbose_name='Название докторской диссертации')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('candidate_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Candidatespecialty', verbose_name='Кандидатская специальность')),
                ('doctor_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Doctorspecialty', verbose_name='Докторская специальность')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Position', verbose_name='Должность')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Rank', verbose_name='Звание')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Subdivision', verbose_name='Подразделение')),
                ('work_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Workstatus', verbose_name='Рабочий статус')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('lastname',),
            },
        ),
    ]
