# Generated by Django 3.0.4 on 2020-04-09 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200331_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Введите корректное значение в поле - Фамилия', regex='^[A-ZА-Я]{1,1}[A-Za-zА-Яа-яЁё,-]{0,}$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Введите корректное значение в поле - Фамилия', regex='^[A-ZА-Я]{1,1}[A-Za-zА-Яа-яЁё,-]{0,}$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Введите корректное значение в поле - Фамилия', regex='^[A-ZА-Я]{1,1}[A-Za-zА-Яа-яЁё,-]{0,}$')], verbose_name='Отчество'),
        ),
    ]
