# Generated by Django 3.0.4 on 2020-04-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0004_auto_20200409_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cityforforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_forum_title', models.CharField(max_length=100, verbose_name='Страна проведения форума')),
            ],
            options={
                'verbose_name': 'Страна проведения форума',
                'verbose_name_plural': 'Страны проведения форума',
                'ordering': ('city_forum_title',),
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.TextField(verbose_name='Название конференции')),
                ('conference_name_short', models.TextField(blank=True, null=True, verbose_name='Название конференции(сокращенное)')),
                ('forum_date', models.DateField(blank=True, null=True, verbose_name='Дата проведения')),
                ('forum_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Cityforforum', verbose_name='Страна проведения')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
                'ordering': ('conference_name',),
            },
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_name', models.CharField(max_length=255)),
                ('in_vak', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сборник статей',
                'verbose_name_plural': 'Сборники статей',
                'ordering': ('digest_name',),
            },
        ),
        migrations.CreateModel(
            name='Grif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grif_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Гриф',
                'verbose_name_plural': 'Грифы',
                'ordering': ('grif_name',),
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'В чьих интересах',
                'verbose_name_plural': 'В чьих интересах',
                'ordering': ('interest_name',),
            },
        ),
        migrations.CreateModel(
            name='InternationalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Международная база научного тестирования',
                'verbose_name_plural': 'Международные базы научного тестирования',
                'ordering': ('base_name',),
            },
        ),
        migrations.CreateModel(
            name='Kindkonf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_name', models.CharField(max_length=255, verbose_name='Вид научного форума')),
            ],
            options={
                'verbose_name': 'Вид научного форума',
                'verbose_name_plural': 'Виды научных форумов',
                'ordering': ('kind_name',),
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_name', models.CharField(max_length=255)),
                ('in_vak', models.BooleanField(blank=True, null=True)),
                ('in_international', models.ManyToManyField(blank=True, null=True, to='sciencework.InternationalBase', verbose_name='Международная база научного цитирования')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ('magazine_name',),
            },
        ),
        migrations.CreateModel(
            name='Organizatorforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, verbose_name='Организатор форума')),
            ],
            options={
                'verbose_name': 'Организатор форума',
                'verbose_name_plural': 'Организаторы форумов',
                'ordering': ('org_name',),
            },
        ),
        migrations.CreateModel(
            name='Orgfounder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, verbose_name='Организация учредитель сборника')),
            ],
            options={
                'verbose_name': 'Организация учредитель сборника',
                'verbose_name_plural': 'Организации учредители сборников',
                'ordering': ('org_name',),
            },
        ),
        migrations.CreateModel(
            name='Publicationkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_kind', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Вид публикации',
                'verbose_name_plural': 'Виды публикации',
                'ordering': ('publication_kind',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=255, verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
                'ordering': ('publisher_name',),
            },
        ),
        migrations.CreateModel(
            name='Statuskonf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255, verbose_name='Статус научного форума')),
            ],
            options={
                'verbose_name': 'Статус начного форума',
                'verbose_name_plural': 'Статусы научных форумов',
                'ordering': ('status_name',),
            },
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Подвид научного издания')),
            ],
            options={
                'verbose_name': 'Подвид учебного издания',
                'verbose_name_plural': 'Подвиды учебных изданий',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Sciencework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('half_year', models.CharField(default='Не указано', max_length=100, verbose_name='Полугодие')),
                ('output_data', models.TextField(blank=True, null=True, verbose_name='Выходные данные')),
                ('sheet_count', models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество печатных листов')),
                ('in_vak', models.BooleanField(blank=True, null=True, verbose_name='Является работой ВАК')),
                ('work_is_foreignauthors', models.BooleanField(blank=True, null=True, verbose_name='Участие сторонних авторов')),
                ('author_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество авторов')),
                ('sciencework_student_participation', models.BooleanField(blank=True, default=False, null=True, verbose_name='Участие обучающихся')),
                ('forum_date', models.DateField(blank=True, null=True, verbose_name='Дата проведения форума')),
                ('authors', models.ManyToManyField(to='authors.Author', verbose_name='Авторы')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Conference', verbose_name='Конференция')),
                ('digest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Digest', verbose_name='Сборник статей')),
                ('forum_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Cityforforum', verbose_name='Страна проведения научного форума')),
                ('forumstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Statuskonf', verbose_name='Статус научного форума')),
                ('grif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Grif', verbose_name='Гриф')),
                ('in_internationals', models.ManyToManyField(to='sciencework.InternationalBase', verbose_name='Входит в международную базу научного цитирования')),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Interest', verbose_name='В чьиъ интересах')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Publicationkind', verbose_name='Вид научной работы')),
                ('kind_forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Kindkonf', verbose_name='Вид форума')),
                ('magazine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Magazine', verbose_name='Журнал')),
                ('org_founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Orgfounder', verbose_name='Организация учредитель сборника')),
                ('organizator_forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Organizatorforum', verbose_name='Организатор научного форума')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Publisher', verbose_name='Издатель')),
                ('subdivisions', models.ManyToManyField(to='authors.Subdivision', verbose_name='Подразделения')),
                ('subspecies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Subspecies', verbose_name='Подвид учебного издания')),
            ],
            options={
                'verbose_name': 'Научная работа',
                'verbose_name_plural': 'Научная работа',
                'ordering': ('kind',),
            },
        ),
        migrations.AddField(
            model_name='digest',
            name='in_international',
            field=models.ManyToManyField(blank=True, null=True, to='sciencework.InternationalBase', verbose_name='Международная база научного цитирования'),
        ),
        migrations.AddField(
            model_name='conference',
            name='forum_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Statuskonf', verbose_name='Статус научного форума'),
        ),
        migrations.AddField(
            model_name='conference',
            name='kind_forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Kindkonf', verbose_name='Вид научного форума'),
        ),
        migrations.AddField(
            model_name='conference',
            name='moderators',
            field=models.ManyToManyField(blank=True, to='authors.Author', verbose_name='Модераторы научного форума/руководители секции'),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizator_forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Organizatorforum', verbose_name='Организатор научного форума'),
        ),
    ]
