# Generated by Django 3.0.4 on 2020-04-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencework', '0002_auto_20200409_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='digest_name',
            field=models.CharField(max_length=255, verbose_name='Название сборника статей'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='in_vak',
            field=models.BooleanField(blank=True, null=True, verbose_name='В ВАК'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest_name',
            field=models.CharField(max_length=255, verbose_name='В чьих интересах'),
        ),
        migrations.AlterField(
            model_name='internationalbase',
            name='base_name',
            field=models.CharField(max_length=255, verbose_name='Международная база научного цитирования'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='in_vak',
            field=models.BooleanField(blank=True, null=True, verbose_name='В ВАК'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='magazine_name',
            field=models.CharField(max_length=255, verbose_name='Название журнала'),
        ),
        migrations.AlterField(
            model_name='sciencework',
            name='half_year',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Полугодие'),
        ),
    ]
