# Generated by Django 3.0.4 on 2020-04-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencework', '0003_auto_20200409_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciencework',
            name='in_internationals',
            field=models.ManyToManyField(blank=True, to='sciencework.InternationalBase', verbose_name='Входит в международную базу научного цитирования'),
        ),
    ]
