# Generated by Django 3.0.4 on 2020-04-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciencework', '0004_auto_20200409_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciencework',
            name='half_year',
            field=models.CharField(default='Не указано', max_length=10, verbose_name='Полугодие'),
        ),
        migrations.AlterField(
            model_name='sciencework',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Interest', verbose_name='В чьих интересах'),
        ),
        migrations.AlterField(
            model_name='sciencework',
            name='output_data',
            field=models.TextField(verbose_name='Выходные данные'),
        ),
        migrations.AlterField(
            model_name='sciencework',
            name='year',
            field=models.IntegerField(verbose_name='Год издания'),
        ),
    ]
