# Generated by Django 3.0.4 on 2020-04-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciencework', '0005_auto_20200409_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciencework',
            name='forum_country',
        ),
        migrations.RemoveField(
            model_name='sciencework',
            name='forum_date',
        ),
        migrations.RemoveField(
            model_name='sciencework',
            name='forumstatus',
        ),
        migrations.RemoveField(
            model_name='sciencework',
            name='kind_forum',
        ),
        migrations.RemoveField(
            model_name='sciencework',
            name='organizator_forum',
        ),
    ]
