# Generated by Django 3.0.4 on 2020-04-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencework', '0007_auto_20200417_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciencework',
            name='author_count',
        ),
        migrations.AddField(
            model_name='sciencework',
            name='other_author_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество сторонних авторов'),
        ),
    ]
