# Generated by Django 3.0.4 on 2020-04-17 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='activity_class',
            field=models.CharField(max_length=100, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='activity_date',
            field=models.DateTimeField(null=True, verbose_name='Дата активности'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
