# Generated by Django 3.0.4 on 2020-04-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200417_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ('-activity_date',), 'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
    ]
