# Generated by Django 3.0.4 on 2020-04-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=255, verbose_name='Критерий')),
                ('value', models.IntegerField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Критерий рейтинга',
                'verbose_name_plural': 'Критерии рейтинга',
                'ordering': ('criterion',),
            },
        ),
        migrations.CreateModel(
            name='RatingTableSubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Рейтинг в баллах')),
                ('place', models.IntegerField(verbose_name='Итоговое место')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Subdivision', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Рейтинг кафедры',
                'verbose_name_plural': 'Рейтинги кафедр',
                'ordering': ('subdivision',),
            },
        ),
        migrations.CreateModel(
            name='RatingTableEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Рейтинг в баллах')),
                ('place', models.IntegerField(verbose_name='Итоговое место')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Рейтинг сотрудника',
                'verbose_name_plural': 'Рейтинги сотрудников',
                'ordering': ('author',),
            },
        ),
    ]
