# Generated by Django 3.0.4 on 2020-04-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anr',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год внедрения'),
        ),
        migrations.AlterField(
            model_name='anr',
            name='approve_date',
            field=models.DateField(verbose_name='Дата утверждения акта'),
        ),
    ]
