# Generated by Django 3.0.4 on 2020-04-30 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonNIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_name', models.CharField(max_length=255, verbose_name='Основание для проведения НИР')),
            ],
            options={
                'verbose_name': 'Основание для проведения НИР',
                'verbose_name_plural': 'Основания для проведения НИР',
                'ordering': ('reason_name',),
            },
        ),
        migrations.CreateModel(
            name='ResearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_result_name', models.CharField(max_length=255, verbose_name='Результат исследования')),
            ],
            options={
                'verbose_name': 'Результат исследования',
                'verbose_name_plural': 'Результаты исследования',
                'ordering': ('research_result_name',),
            },
        ),
        migrations.CreateModel(
            name='NIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nir_title', models.TextField()),
                ('plan_item', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт плана для проведения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('approve_date', models.DateField(blank=True, null=True, verbose_name='Дата утверждения акта')),
                ('date_added', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время моследнего изменения')),
                ('authors', models.ManyToManyField(to='authors.Author', verbose_name='Авторы НИР')),
                ('leader_subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nir_leader_subdivision', to='authors.Subdivision', verbose_name='Подразделение научного руководителя')),
                ('nir_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nir_leader', to='authors.Author', verbose_name='Научный руководитель')),
                ('reason', models.ManyToManyField(to='nir.ReasonNIR', verbose_name='Основания для проведения')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nir.ResearchResults', verbose_name='Результат проведения НИР')),
                ('subdivisions', models.ManyToManyField(to='authors.Subdivision', verbose_name='Подразделения НИР')),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем внесено/изменено')),
            ],
            options={
                'verbose_name': 'Научно-исследовательская работа',
                'verbose_name_plural': 'Научно-исследовательские работы',
                'ordering': ('nir_title',),
            },
        ),
    ]
