# Generated by Django 3.0.4 on 2020-04-17 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nir', '0002_delete_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='nir',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время моследнего изменения'),
        ),
        migrations.AddField(
            model_name='nir',
            name='user_added',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем внесено/изменено'),
        ),
    ]
